apiVersion: v1
kind: Service
metadata:
  name: mf1-service
spec:
  type: LoadBalancer
  selector:
    app: mf1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
