# ==== CONFIGURE =====
# Use a Node 18 base image
FROM node:18-alpine 
# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files
COPY . .
COPY package.json yarn.json
# ==== BUILD =====
# Install dependencies
RUN yarn install --frozen-lockfile
# Build the app
RUN yarn run build
# ==== RUN =======
# Set the env to "production"
ENV NODE_ENV production
# Expose the port on which the app will be running
EXPOSE 3000
# Start the app
CMD [ "yarn", "build:start" ]

# FROM nginx:stable-alpine
# COPY dist/ /usr/share/nginx/html 