# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: http-ingress
#   annotations:
#     kubernetes.io/ingress.class: public
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /mf1
#             pathType: Prefix
#             backend:
#               service:
#                 name: mf1
#                 port:
#                   number: 80
#           - path: /mf2
#             pathType: Prefix
#             backend:
#               service:
#                 name: mf2
#                 port:
#                   number: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /mf1/(.*)
            pathType: Prefix
            backend:
              service:
                name: mf1
                port:
                  number: 80
          - path: /mf2/(.*)
            pathType: Prefix
            backend:
              service:
                name: mf2
                port:
                  number: 80
